INSERT INTO `carsdb`.`brand` (`brandid`, `brandname`) VALUES ('10001', 'ABARTH');
INSERT INTO `carsdb`.`brand` (`brandid`, `brandname`) VALUES ('10002', 'ACURA');
INSERT INTO `carsdb`.`brand` (`brandid`, `brandname`) VALUES ('10003', 'ALFA ROMEO');
INSERT INTO `carsdb`.`brand` (`brandid`, `brandname`) VALUES ('10004', 'ALUMI CRAFT');
INSERT INTO `carsdb`.`brand` (`brandid`, `brandname`) VALUES ('10005', 'AMC');
INSERT INTO `carsdb`.`brand` (`brandid`, `brandname`) VALUES ('10006', 'AMG Transport Dynamics');
INSERT INTO `carsdb`.`brand` (`brandid`, `brandname`) VALUES ('10007', 'ARIEL');
INSERT INTO `carsdb`.`brand` (`brandid`, `brandname`) VALUES ('10008', 'ASCARI');
INSERT INTO `carsdb`.`brand` (`brandid`, `brandname`) VALUES ('10009', 'ASTON MARTIN');
INSERT INTO `carsdb`.`brand` (`brandid`, `brandname`) VALUES ('10010', 'AUDI');
INSERT INTO `carsdb`.`brand` (`brandid`, `brandname`) VALUES ('10011', 'AUSTIN-HEALEY');
INSERT INTO `carsdb`.`brand` (`brandid`, `brandname`) VALUES ('10012', 'AUTO UNION');
INSERT INTO `carsdb`.`brand` (`brandid`, `brandname`) VALUES ('10013', 'BAC');
INSERT INTO `carsdb`.`brand` (`brandid`, `brandname`) VALUES ('10014', 'BENTLEY');
INSERT INTO `carsdb`.`brand` (`brandid`, `brandname`) VALUES ('10015', 'BMW');
INSERT INTO `carsdb`.`brand` (`brandid`, `brandname`) VALUES ('10016', 'BOWLER');
INSERT INTO `carsdb`.`brand` (`brandid`, `brandname`) VALUES ('10017', 'BUGATTI');
INSERT INTO `carsdb`.`brand` (`brandid`, `brandname`) VALUES ('10018', 'BUICK');
INSERT INTO `carsdb`.`brand` (`brandid`, `brandname`) VALUES ('10019', 'CADILLAC');
INSERT INTO `carsdb`.`brand` (`brandid`, `brandname`) VALUES ('10020', 'CAN-AM');
INSERT INTO `carsdb`.`brand` (`brandid`, `brandname`) VALUES ('10021', 'CATERHAM');
INSERT INTO `carsdb`.`brand` (`brandid`, `brandname`) VALUES ('10022', 'CHEVROLET');
INSERT INTO `carsdb`.`brand` (`brandid`, `brandname`) VALUES ('10023', 'CHRYSLER');
INSERT INTO `carsdb`.`brand` (`brandid`, `brandname`) VALUES ('10024', 'DATSUN');
INSERT INTO `carsdb`.`brand` (`brandid`, `brandname`) VALUES ('10025', 'DODGE');
INSERT INTO `carsdb`.`brand` (`brandid`, `brandname`) VALUES ('10026', 'DONKERVOORT');
INSERT INTO `carsdb`.`brand` (`brandid`, `brandname`) VALUES ('10027', 'EAGLE');
INSERT INTO `carsdb`.`brand` (`brandid`, `brandname`) VALUES ('10028', 'EXOMOTIVE');
INSERT INTO `carsdb`.`brand` (`brandid`, `brandname`) VALUES ('10029', 'FERRARI');
INSERT INTO `carsdb`.`brand` (`brandid`, `brandname`) VALUES ('10030', 'FIAT');
INSERT INTO `carsdb`.`brand` (`brandid`, `brandname`) VALUES ('10031', 'FORD');
INSERT INTO `carsdb`.`brand` (`brandid`, `brandname`) VALUES ('10032', 'FUNCO Motorsports');
INSERT INTO `carsdb`.`brand` (`brandid`, `brandname`) VALUES ('10033', 'GMC');
INSERT INTO `carsdb`.`brand` (`brandid`, `brandname`) VALUES ('10034', 'HDT');
INSERT INTO `carsdb`.`brand` (`brandid`, `brandname`) VALUES ('10035', 'HENNESSY');
INSERT INTO `carsdb`.`brand` (`brandid`, `brandname`) VALUES ('10036', 'HILLMAN');
INSERT INTO `carsdb`.`brand` (`brandid`, `brandname`) VALUES ('10037', 'HOLDEN');
INSERT INTO `carsdb`.`brand` (`brandid`, `brandname`) VALUES ('10038', 'HONDA');
INSERT INTO `carsdb`.`brand` (`brandid`, `brandname`) VALUES ('10039', 'HSV');
INSERT INTO `carsdb`.`brand` (`brandid`, `brandname`) VALUES ('10040', 'HYUNDAI');
INSERT INTO `carsdb`.`brand` (`brandid`, `brandname`) VALUES ('10041', 'INFINITI');
INSERT INTO `carsdb`.`brand` (`brandid`, `brandname`) VALUES ('10042', 'INTERNATIONAL');
INSERT INTO `carsdb`.`brand` (`brandid`, `brandname`) VALUES ('10043', 'JAGUAR');
INSERT INTO `carsdb`.`brand` (`brandid`, `brandname`) VALUES ('10044', 'JEEP');
INSERT INTO `carsdb`.`brand` (`brandid`, `brandname`) VALUES ('10045', 'KIA');
INSERT INTO `carsdb`.`brand` (`brandid`, `brandname`) VALUES ('10046', 'KOENIGSEGG');
INSERT INTO `carsdb`.`brand` (`brandid`, `brandname`) VALUES ('10047', 'KTM');
INSERT INTO `carsdb`.`brand` (`brandid`, `brandname`) VALUES ('10048', 'LAMBORGHINI');
INSERT INTO `carsdb`.`brand` (`brandid`, `brandname`) VALUES ('10049', 'LANCIA');
INSERT INTO `carsdb`.`brand` (`brandid`, `brandname`) VALUES ('10050', 'LAND ROVER');
INSERT INTO `carsdb`.`brand` (`brandid`, `brandname`) VALUES ('10051', 'LOCAL MOTORS');
INSERT INTO `carsdb`.`brand` (`brandid`, `brandname`) VALUES ('10052', 'LOLA');
INSERT INTO `carsdb`.`brand` (`brandid`, `brandname`) VALUES ('10053', 'LOTUS');
INSERT INTO `carsdb`.`brand` (`brandid`, `brandname`) VALUES ('10054', 'MASERATI');
INSERT INTO `carsdb`.`brand` (`brandid`, `brandname`) VALUES ('10055', 'MAZDA');
INSERT INTO `carsdb`.`brand` (`brandid`, `brandname`) VALUES ('10056', 'MCLAREN');
INSERT INTO `carsdb`.`brand` (`brandid`, `brandname`) VALUES ('10057', 'MERCEDES-AMG');
INSERT INTO `carsdb`.`brand` (`brandid`, `brandname`) VALUES ('10058', 'MERCEDES-BENZ');
INSERT INTO `carsdb`.`brand` (`brandid`, `brandname`) VALUES ('10059', 'MERCURY');
INSERT INTO `carsdb`.`brand` (`brandid`, `brandname`) VALUES ('10060', 'MEYERS');
INSERT INTO `carsdb`.`brand` (`brandid`, `brandname`) VALUES ('10061', 'MG');
INSERT INTO `carsdb`.`brand` (`brandid`, `brandname`) VALUES ('10062', 'MINI');
INSERT INTO `carsdb`.`brand` (`brandid`, `brandname`) VALUES ('10063', 'MITSUBSHI');
INSERT INTO `carsdb`.`brand` (`brandid`, `brandname`) VALUES ('10064', 'MORGAN');
INSERT INTO `carsdb`.`brand` (`brandid`, `brandname`) VALUES ('10065', 'MORRIS');
INSERT INTO `carsdb`.`brand` (`brandid`, `brandname`) VALUES ('10066', 'NISSAN');
INSERT INTO `carsdb`.`brand` (`brandid`, `brandname`) VALUES ('10067', 'OLDSMOBILE');
INSERT INTO `carsdb`.`brand` (`brandid`, `brandname`) VALUES ('10068', 'OPEL');
INSERT INTO `carsdb`.`brand` (`brandid`, `brandname`) VALUES ('10069', 'PAGANI');
INSERT INTO `carsdb`.`brand` (`brandid`, `brandname`) VALUES ('10070', 'PEEL');
INSERT INTO `carsdb`.`brand` (`brandid`, `brandname`) VALUES ('10071', 'PEUGEOT');
INSERT INTO `carsdb`.`brand` (`brandid`, `brandname`) VALUES ('10072', 'PLYMOUTH');
INSERT INTO `carsdb`.`brand` (`brandid`, `brandname`) VALUES ('10073', 'POLARIS');
INSERT INTO `carsdb`.`brand` (`brandid`, `brandname`) VALUES ('10074', 'PONTIAC');
INSERT INTO `carsdb`.`brand` (`brandid`, `brandname`) VALUES ('10075', 'PORSCHE');
INSERT INTO `carsdb`.`brand` (`brandid`, `brandname`) VALUES ('10076', 'RADICAL');
INSERT INTO `carsdb`.`brand` (`brandid`, `brandname`) VALUES ('10077', 'RAM');
INSERT INTO `carsdb`.`brand` (`brandid`, `brandname`) VALUES ('10078', 'RELIANT');
INSERT INTO `carsdb`.`brand` (`brandid`, `brandname`) VALUES ('10079', 'RENAULT');
INSERT INTO `carsdb`.`brand` (`brandid`, `brandname`) VALUES ('10080', 'RJ ANDERSON');
INSERT INTO `carsdb`.`brand` (`brandid`, `brandname`) VALUES ('10081', 'SALEEN');
INSERT INTO `carsdb`.`brand` (`brandid`, `brandname`) VALUES ('10082', 'SHELBY');
INSERT INTO `carsdb`.`brand` (`brandid`, `brandname`) VALUES ('10083', 'SPANIA GTA');
INSERT INTO `carsdb`.`brand` (`brandid`, `brandname`) VALUES ('10084', 'SUBARU');
INSERT INTO `carsdb`.`brand` (`brandid`, `brandname`) VALUES ('10085', 'SUNBEAM');
INSERT INTO `carsdb`.`brand` (`brandid`, `brandname`) VALUES ('10086', 'TALBOT');
INSERT INTO `carsdb`.`brand` (`brandid`, `brandname`) VALUES ('10087', 'TAMO');
INSERT INTO `carsdb`.`brand` (`brandid`, `brandname`) VALUES ('10088', 'TERRADYNE');
INSERT INTO `carsdb`.`brand` (`brandid`, `brandname`) VALUES ('10089', 'TOYOTA');
INSERT INTO `carsdb`.`brand` (`brandid`, `brandname`) VALUES ('10090', 'TRIUMPH');
INSERT INTO `carsdb`.`brand` (`brandid`, `brandname`) VALUES ('10091', 'TVR');
INSERT INTO `carsdb`.`brand` (`brandid`, `brandname`) VALUES ('10092', 'VAUXHALL');
INSERT INTO `carsdb`.`brand` (`brandid`, `brandname`) VALUES ('10093', 'VOLKSWAGEN');
INSERT INTO `carsdb`.`brand` (`brandid`, `brandname`) VALUES ('10094', 'VOLVO');
INSERT INTO `carsdb`.`brand` (`brandid`, `brandname`) VALUES ('10095', 'W MOTORS');
INSERT INTO `carsdb`.`brand` (`brandid`, `brandname`) VALUES ('10096', 'WILLYS');
