-- MySQL Script generated by MySQL Workbench
-- Mon May  3 16:47:54 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema carsdb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema carsdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `carsdb` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `carsdb` ;

-- -----------------------------------------------------
-- Table `carsdb`.`brand`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `carsdb`.`brand` ;

CREATE TABLE IF NOT EXISTS `carsdb`.`brand` (
  `brandid` INT NOT NULL,
  `brandname` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`brandid`),
  UNIQUE INDEX `Brand_Name_UNIQUE` (`brandname` ASC) VISIBLE,
  UNIQUE INDEX `Brand_ID_UNIQUE` (`brandid` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `carsdb`.`product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `carsdb`.`product` ;

CREATE TABLE IF NOT EXISTS `carsdb`.`product` (
  `productid` INT NOT NULL,
  `productname` VARCHAR(45) NOT NULL,
  `power` INT NULL DEFAULT NULL,
  `torque` INT NULL DEFAULT NULL,
  `weight` DECIMAL(10,3) NULL DEFAULT NULL,
  `transmission` VARCHAR(3) NULL DEFAULT NULL,
  `yom` DATE NULL DEFAULT NULL,
  `description` VARCHAR(255) NULL DEFAULT NULL,
  `img` VARCHAR(255) NULL,
  `brand_brandid` INT NOT NULL,
  PRIMARY KEY (`productid`),
  UNIQUE INDEX `Product_ID_UNIQUE` (`productid` ASC) VISIBLE,
  UNIQUE INDEX `Name_UNIQUE` (`productname` ASC) VISIBLE,
  INDEX `fk_Product_Brand_idx` (`brand_brandid` ASC) VISIBLE,
  CONSTRAINT `fk_Product_Brand`
    FOREIGN KEY (`brand_brandid`)
    REFERENCES `carsdb`.`brand` (`brandid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `carsdb`.`color`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `carsdb`.`color` ;

CREATE TABLE IF NOT EXISTS `carsdb`.`color` (
  `colorid` INT NOT NULL,
  `colorname` VARCHAR(45) NULL DEFAULT NULL,
  `colorcode` VARCHAR(7) NOT NULL,
  PRIMARY KEY (`colorid`),
  UNIQUE INDEX `Color_ID_UNIQUE` (`colorid` ASC) VISIBLE,
  UNIQUE INDEX `Color_Code_UNIQUE` (`colorcode` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `carsdb`.`productcolor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `carsdb`.`productcolor` ;

CREATE TABLE IF NOT EXISTS `carsdb`.`productcolor` (
  `productid` INT NOT NULL,
  `colorid` INT NOT NULL,
  PRIMARY KEY (`productid`, `colorid`),
  INDEX `fk_Product_has_Color_Color1_idx` (`colorid` ASC) VISIBLE,
  INDEX `fk_Product_has_Color_Product1_idx` (`productid` ASC) VISIBLE,
  CONSTRAINT `fk_Product_has_Color_Product1`
    FOREIGN KEY (`productid`)
    REFERENCES `carsdb`.`product` (`productid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Product_has_Color_Color1`
    FOREIGN KEY (`colorid`)
    REFERENCES `carsdb`.`color` (`colorid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SET SQL_MODE = '';
DROP USER IF EXISTS user1;
SET SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';
CREATE USER 'user1' IDENTIFIED BY 'mysql';

GRANT ALL ON `carsdb`.* TO 'user1';

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
