CREATE USER 'chom'@'%' IDENTIFIED BY 'mysql';
CREATE USER 'kamin'@'%' IDENTIFIED BY 'mysql';

GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, RELOAD, EXECUTE, CREATE VIEW, SHOW VIEW, CREATE ROLE, DROP ROLE ON *.* TO `chom`@`%` WITH GRANT OPTION;
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, RELOAD, EXECUTE, CREATE VIEW, SHOW VIEW, CREATE ROLE, DROP ROLE ON *.* TO `kamin`@`%` WITH GRANT OPTION;

commit;